/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDownloadProxyRouteImport } from './routes/api/public/download-proxy'
import { Route as ApiPublicExtractAudioRouteImport } from './routes/api/public/extract-audio'
import { Route as ApiPublicFetchVideoRouteImport } from './routes/api/public/fetch-video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadProxyRoute = ApiPublicDownloadProxyRouteImport.update({
  id: '/api/public/download-proxy',
  path: '/api/public/download-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractAudioRoute = ApiPublicExtractAudioRouteImport.update({
  id: '/api/public/extract-audio',
  path: '/api/public/extract-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFetchVideoRoute = ApiPublicFetchVideoRouteImport.update({
  id: '/api/public/fetch-video',
  path: '/api/public/fetch-video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/download-proxy': typeof ApiPublicDownloadProxyRoute
  '/api/public/extract-audio': typeof ApiPublicExtractAudioRoute
  '/api/public/fetch-video': typeof ApiPublicFetchVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/download-proxy': typeof ApiPublicDownloadProxyRoute
  '/api/public/extract-audio': typeof ApiPublicExtractAudioRoute
  '/api/public/fetch-video': typeof ApiPublicFetchVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/download-proxy': typeof ApiPublicDownloadProxyRoute
  '/api/public/extract-audio': typeof ApiPublicExtractAudioRoute
  '/api/public/fetch-video': typeof ApiPublicFetchVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/download-proxy'
    | '/api/public/extract-audio'
    | '/api/public/fetch-video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/download-proxy'
    | '/api/public/extract-audio'
    | '/api/public/fetch-video'
  id:
    | '__root__'
    | '/'
    | '/api/public/download-proxy'
    | '/api/public/extract-audio'
    | '/api/public/fetch-video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDownloadProxyRoute: typeof ApiPublicDownloadProxyRoute
  ApiPublicExtractAudioRoute: typeof ApiPublicExtractAudioRoute
  ApiPublicFetchVideoRoute: typeof ApiPublicFetchVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-proxy': {
      id: '/api/public/download-proxy'
      path: '/api/public/download-proxy'
      fullPath: '/api/public/download-proxy'
      preLoaderRoute: typeof ApiPublicDownloadProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-audio': {
      id: '/api/public/extract-audio'
      path: '/api/public/extract-audio'
      fullPath: '/api/public/extract-audio'
      preLoaderRoute: typeof ApiPublicExtractAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fetch-video': {
      id: '/api/public/fetch-video'
      path: '/api/public/fetch-video'
      fullPath: '/api/public/fetch-video'
      preLoaderRoute: typeof ApiPublicFetchVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDownloadProxyRoute: ApiPublicDownloadProxyRoute,
  ApiPublicExtractAudioRoute: ApiPublicExtractAudioRoute,
  ApiPublicFetchVideoRoute: ApiPublicFetchVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
